### ISSUE TITLE
Deadsimplewhiteboard

### ISSUE THREAD

**Issue by ravipal86** [mlakkadshaw/Deadsimplewhiteboard#1]
Is it possible to use database with whiteboard to keep whiteboard persistent ?

**Comment by mlakkadshaw** [comment]
Yes, at regular intervals we can export the whiteboard data into json and
use redis to store it.

**Comment by ravipal86** [comment]
is it possible to give me an example so i can test with database. to make sure persistent whiteboard.

**Comment by cailin186** [comment]
i want host this in my server.how to install this board,thank you

**Comment by mlakkadshaw** [comment]
To install it on your server, follow these steps:
1. Install node.js on your computer
2. Clone this repo
3. cd into the directory where you have cloned this repo
4. run `npm install`
5. run `node app.js`

**Comment by yanzhou-share** [comment]
please tell me that the code of server of  connection  between two persons @mlakkadshaw

**Comment by mlakkadshaw** [comment]
@yanzhou-share this is the server code https://github.com/mlakkadshaw/Deadsimplewhiteboard/blob/master/app.js#L84
